Grouper-Server/config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :members
    resources :alarms do
      member do
        post 'set'
      end
    end
    resources :boards do
      collection do
        get 'edit_index'
      end
    end

    member do
      get 'add_member'
      post 'add_member'
      get 'talk/index'
      post 'talk/index'
      post 'talk/new'
      post 'talk/new_image'
      post 'talk/new_address'
      post 'new_image'
    end
    collection do
      get 'talk_index'
      get 'board_index'
      get 'alarm_index'
      post 'talk/get_address'
    end
  end

  get 'user/find_group'
  post 'user/find_group'
  post 'user/new_image' => 'user#new_image'

  devise_for :users, :controllers => { 
    :sessions => "users/sessions",
    :registrations => 'users/registrations'
  }

  root 'user#index'

end

Grouper-Server/app/models/member.rb
class Member < ActiveRecord::Base
  belongs_to :group
end

Grouper-Server/app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update]

  # GET /members
  # GET /members.json
  def index
    @members = Member.where(group_id: params[:group_id])
    @group = Group.find(params[:group_id])
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'ユーザを作成しました' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'メンバー情報を更新しました' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    group = Group.find(params[:group_id])
    @member = group.members.find_by(user_id: params[:id])
    @member.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'グループから退会しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:group_id, :user_id)
    end
end

Grouper-Server/app/helpers/members_helper.rb
module MembersHelper
end

Grouper-Server/app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    グループID<br>
    <%= f.number_field :group_id, class: "form-control" %>
  </div>
  <div class="field">
    ユーザID<br>
    <%= f.number_field :user_id, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success btn-lg btn-block", value: "追加" %>
  </div>
<% end %>

Grouper-Server/app/views/members/edit.html.erb
<h1>ユーザ情報編集</h1>

<%= render 'form' %>

<%= link_to '見る', @member %>
<%= link_to '戻る', members_path %>

Grouper-Server/app/views/members/index.html.erb
<h1>ユーザ一覧</h1>

<strong><%= @group.name %></strong>
<ul>
<% @members.each do |member| %>
  <li><%= user_name(member.user_id) %></li>
<% end %>
</ul>

<%= link_to '戻る', groups_path, class: "foot btn btn-default btn-lg btn-block" %>

Grouper-Server/app/views/members/new.html.erb
<h1>メンバー追加</h1>

<%= render 'form' %>

<%= link_to '戻る', group_path, class: "btn btn-default btn-lg btn-block" %>

Grouper-Server/app/views/members/show.html.erb
<!--
<p>
<strong>参加しているグループ</strong><br>
<%= @member.group.name %>
</p
-->

<p>
<strong>ユーザID</strong><br>
<%= @member.user_id %>
</p>

<p>
<strong>ユーザ名</strong><br>
<%= user_email(@member.user_id) %>

<%= link_to '戻る', group_path, class: "btn btn-default btn-lg btn-block" %>