Grouper-Server/config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :members
    resources :alarms do
      member do
        post 'set'
      end
    end
    resources :boards do
      collection do
        get 'edit_index'
      end
    end

    member do
      get 'add_member'
      post 'add_member'
      get 'talk/index'
      post 'talk/index'
      post 'talk/new'
      post 'talk/new_image'
      post 'talk/new_address'
      post 'new_image'
    end
    collection do
      get 'talk_index'
      get 'board_index'
      get 'alarm_index'
      post 'talk/get_address'
    end
  end

  get 'user/find_group'
  post 'user/find_group'
  post 'user/new_image' => 'user#new_image'

  devise_for :users, :controllers => { 
    :sessions => "users/sessions",
    :registrations => 'users/registrations'
  }

  root 'user#index'

end

Grouper-Server/app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :group
end

Grouper-Server/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    group = Group.find(params[:group_id])
    @boards = group.boards
  end

  
  def edit_index 
    group = Group.find(params[:group_id])
    @boards = group.boards
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @group = Group.find(params[:group_id])
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
    @group = Group.find(params[:group_id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @board.group_id = params[:group_id]

    respond_to do |format|
      if @board.save
        format.html { redirect_to edit_index_group_boards_path(), notice: '掲示を作成しました' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to edit_index_group_boards_path, notice: '掲示を更新しました' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to edit_index_group_boards_path, notice: '掲示を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :description, :group_id)
    end
end

Grouper-Server/app/helpers/boards_helper.rb
module BoardsHelper
end

Grouper-Server/app/views/boards/_form.html.erb
<%= form_for [@group, @board] do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>タイトル(15字以内)</label>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <label>詳細(50字以内)</label>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :送信 , class: "btn btn-lg btn-block btn-success" %>
  </div>
<% end %>

Grouper-Server/app/views/boards/edit.html.erb
<%= render 'form' %>

<%= link_to '戻る', group_boards_path, class: 'btn btn-lg btn-default btn-block' %>

Grouper-Server/app/views/boards/edit_index.html.erb
<div class="row">
<table class="edit_board_all">
  <thead>
    <tr>
      <th class="col-xs-4">タイトル</th>
      <th class="col-xs-6">詳細</th>
      <th class="col-xs-2">編集</th>
    </tr>
  </thead>

  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.title %></td>
        <td><%= board.description %></td>
        <td><%= link_to '編集', edit_group_board_path(board.group_id, board), class:"btn btn-success" %>
        <%= link_to '削除', group_board_path(board.group_id, board), method: :delete, data: { confirm: '削除してもいいですか？' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "新しい掲示板", "../boards/new", class: "btn btn-lg btn-block btn-success back_to_board" %>
<%= link_to "掲示板へ戻る", "../boards", class: "btn btn-lg btn-block btn-primary back_to_board" %>
<br>

Grouper-Server/app/views/boards/index.html.erb
<div id="board" class="carousel slide" data-ride="carousel">
  <!--
  <ol class="carousel-indicators">
    <li data-target="#board" data-slide-to="0" class="active"></li>
    <li data-target="#board" data-slide-to="1"></li>
    <li data-target="#board" data-slide-to="2"></li>
  </ol>
  -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag('carousel.png', style: 'width: 70%') %>
      <div class="carousel-caption">
        <h3 class="board-top">災害時掲示板</h3>
      </div>
    </div>
    <% @boards.each do |board| %>
      <div class="item">
        <%= image_tag('carousel.png', style: 'width: 70%') %> 
        <div class="carousel-caption">
            <div class="board board-main">
              <h3 class="board board-title"><%= board.title %></h3>
              <p class="board board-description"><%= board.description %></p>
            </div>
        </div>
      </div>
    <% end %>
  </div>

  <a class="left carousel-control" href="#board" role="button" data-slide="prev"></a>
  <a class="right carousel-control" href="#board" role="button" data-slide="next"></a>
</div>

  <%= link_to '新しい掲示板', new_group_board_path, class: "btn btn-lg btn-block btn-primary" %>
  <%= link_to '掲示板の編集', "boards/edit_index", class: "btn btn-lg btn-block btn-success" %>

Grouper-Server/app/views/boards/new.html.erb
<%= render 'form' %>

<%= link_to '戻る', group_boards_path, class: "btn btn-lg btn-block btn-default" %>

Grouper-Server/app/views/boards/show.html.erb
<p>
  <strong>タイトル</strong>
  <%= @board.title %>
</p>

<p>
  <strong>詳細</strong>
  <%= @board.description %>
</p>

<p>
  <strong>グループID</strong>
  <%= @board.group_id %>
</p>

<%= link_to '編集', edit_board_path(@board) , class: "btn btn-block btn-lg btn-success" %>
<%= link_to '戻る', boards_path, class: "btn btn-block btn-lg btn-default" %>