Grouper-Server/config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :members
    resources :alarms do
      member do
        post 'set'
      end
    end
    resources :boards do
      collection do
        get 'edit_index'
      end
    end

    member do
      get 'add_member'
      post 'add_member'
      get 'talk/index'
      post 'talk/index'
      post 'talk/new'
      post 'talk/new_image'
      post 'talk/new_address'
      post 'new_image'
    end
    collection do
      get 'talk_index'
      get 'board_index'
      get 'alarm_index'
      post 'talk/get_address'
    end
  end

  get 'user/find_group'
  post 'user/find_group'
  post 'user/new_image' => 'user#new_image'

  devise_for :users, :controllers => { 
    :sessions => "users/sessions",
    :registrations => 'users/registrations'
  }

  root 'user#index'

end

Grouper-Server/app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :members, :dependent => :destroy
  has_many :talks, :dependent => :destroy
  has_many :boards, :dependent => :destroy
  has_many :alarms, :dependent => :destroy

  validates_presence_of :name, message: "グループ名は必須です"
end

Grouper-Server/app/controllers/groups_controller.rb
require 'pp'
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :add_member]
  protect_from_forgery except: :new_image

  # GET /groups
  # GET /groups.json
  def index
    members = Member.where(user_id: current_user.id)
    @groups = Array.new
    members.each do |member|
      @groups.push Group.find(member.group_id)
    end
  end

  def talk_index
    members = Member.where(user_id: current_user.id)
    @groups = Array.new
    members.each do |member|
      @groups.push Group.find(member.group_id)
    end
  end

  def board_index
    members = Member.where(user_id: current_user.id)
    @groups = Array.new
    members.each do |member|
      @groups.push Group.find(member.group_id)
    end
  end

  def alarm_index
    members = Member.where(user_id: current_user.id)
    @groups = Array.new
    members.each do |member|
      @groups.push Group.find(member.group_id)
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @members = @group.members
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end
  
  def add_member
    @user = current_user
    if @group.members.exists?(user_id: @user.id)
      flash[:notice] = "すでにグループに入っています"
      redirect_to user_find_group_path
    end


    if params[:add] == "true"
      if @group.members.exists?(user_id: @user.id) 
        flash[:notice] = "すでにグループに入っています"
      else
        @group.members.create(user_id: @user.id)
      end
      redirect_to @group
    else
      @members = @group.members
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @user = current_user
    @group.user_id = @user.id


    respond_to do |format|
      if @group.save
        @group.members.create(user_id: @user.id)
        format.html { redirect_to @group, notice: 'グループを作成しました' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    pp params

    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'グループを更新しました' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'グループを削除しました' }
      format.json { head :no_content }
    end
  end

  def new_image
    group = Group.find(params[:id])
    image = params[:upload]
    File.open('./public/img/group/' + group.id.to_s, 'wb') do |of|
      of.write(image[:file].read)
    end
    redirect_to edit_group_path(group)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:user_id, :name, :description)
    end
end

Grouper-Server/app/helpers/groups_helper.rb
module GroupsHelper
end

Grouper-Server/app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <% @group.errors.full_messages.each do |message| %>
        <%= message.delete("Name ") %>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <% if @group.errors.any? %>
      <div class="form-group has-error">
        <label>グループ名</label>
        <%= f.text_field :name, class: "form-control input-lg" %>
      </div>
    <% else %>
      <div class="form-group">
        <label>グループ名</label>
        <%= f.text_field :name, class: "form-control input-lg" %>
      </div>
    <% end %>
  </div>
  <div class="field">
    <div class="form-group">
      <label>詳細</label>
      <%= f.text_area :description, class: "form-control input-lg" %>
    </div>
  </div>
  <div class="actions">
    <%= submit_tag "作成", class:"btn btn-success btn-lg btn-block", value: "作成"%>
  </div>
<% end %>
<% if @group.id != nil %>
  <%= form_tag(new_image_group_path(@group.id), remote: true, multipart: true, class: "add-img-form") do %>
    <div class="field add-img-form">
      <label>画像</label><br>
      <div class="col-xs-6"><img src="" id="preview"></div>
      <%= file_field :upload, :file , id: "exampleInputFile", style: "display:none;" %>
      <div class="col-xs-3"><a id="btnUpload" class="easyui-linkbutton btn btn btn-primary" data-options="iconCls:'icon-save'">選択</a></div>
      <div class="col-xs-3"><%= submit_tag "更新", class: "btn btn-success btn" %></div>
    </div>
  <% end %>
<% end %>

Grouper-Server/app/views/groups/add_member.html.erb
<div class="container">
<h2><%= @group.name %></h2>
<h3><%= @group.description %></h3>


<p>
<%= button_to 'このグループに参加する', add_member_group_path(@group.id, add: "true"), class: "btn btn-lg btn-primary btn-block" %>
</p>
<p>
<% link_to "戻る", :back, class: "btn btn-lg btn-block btn-default" %>
</div>

Grouper-Server/app/views/groups/alarm_index.html.erb
<table class="group-table table table-hover">
  <% @groups.each do |group| %>
    <tr class="group-tr">
    <th class="col-xs-2 img">
      <!-- <%= link_to image_tag('dummy.png', class: 'img-circle group-img pull-left', style: 'width: 64px; height: 64px;'), {:action=>"index", :controller=>"talk", :id=>group.id}  %> -->
      <a href="/groups/<%= group.id %>/alarms">
      <% if File.exist?("./public/img/group/" + group.id.to_s) %>
        <img src="/img/group/<%= group.id %>" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% else %>
        <img src="/group/default.png" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% end %>
    </a>
    </th>
    <th class="col-xs-9 name">
      <!-- <%= link_to group.name, {:action=>"index", :controller=>"talk", :id=>group.id}, class: "group_link" %> -->
      <%= link_to group.name, group_alarms_path(group) %>
    </th>
    <th class="col-xs-1 remove">
      <%= link_to '退会', group_member_path(group.id, current_user.id), method: :delete, data: {confirm: '本当に退会しますか？' }, class: "btn btn-danger btn pull-right group_destroy" %>
    </th>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくグループを作る', new_group_path, class: "new_group btn btn-success btn-lg btn-block" %>

Grouper-Server/app/views/groups/board_index.html.erb
<table class="group-table table table-hover">
  <% @groups.each do |group| %>
    <tr class="group-tr">
    <th class="col-xs-2 img">
      <!-- <%= link_to image_tag('dummy.png', class: 'img-circle group-img pull-left', style: 'width: 64px; height: 64px;'), {:action=>"index", :controller=>"talk", :id=>group.id}  %> -->
      <a href="/groups/<%= group.id %>/boards">
      <% if File.exist?("./public/img/group/" + group.id.to_s) %>
        <img src="/img/group/<%= group.id %>" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% else %>
        <img src="/group/default.png" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% end %>
    </a>
    </th>
    <th class="col-xs-9 name">
      <!-- <%= link_to group.name, {:action=>"index", :controller=>"talk", :id=>group.id}, class: "group_link" %> -->
      <%= link_to group.name, group_boards_path(group) %>
    </th>
    <th class="col-xs-1 remove">
      <%= link_to '退会', group_member_path(group.id, current_user.id), method: :delete, data: {confirm: '本当に退会しますか？' }, class: "btn btn-danger btn pull-right group_destroy" %>
    </th>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくグループを作る', new_group_path, class: "new_group btn btn-success btn-lg btn-block" %>

Grouper-Server/app/views/groups/edit.html.erb
<h1>グループ設定</h1>

<%= render 'form' %>
<%= link_to 'グループ削除', "./" ,method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-lg btn-block btn-danger" %>
<%= link_to '戻る', @group, class: "btn btn-default btn-lg btn-block" %> 

Grouper-Server/app/views/groups/index.html.erb
<table class="group-table table table-hover">
  <% @groups.each do |group| %>
    <tr class="group-tr">
    <th class="col-xs-2 img">
      <!-- <%= link_to image_tag('dummy.png', class: 'img-circle group-img pull-left', style: 'width: 64px; height: 64px;'), {:action=>"index", :controller=>"talk", :id=>group.id}  %> -->
      <a href="/groups/<%= group.id %>">
      <% if File.exist?("./public/img/group/" + group.id.to_s) %>
        <img src="/img/group/<%= group.id %>" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% else %>
        <img src="/group/default.png" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% end %>
    </a>
    </th>
    <th class="col-xs-9 name">
      <!-- <%= link_to group.name, {:action=>"index", :controller=>"talk", :id=>group.id}, class: "group_link" %> -->
      <%= link_to group.name, group %>
    </th>
    <th class="col-xs-1 remove">
      <%= link_to '退会', group_member_path(group.id, current_user.id), method: :delete, data: {confirm: '本当に退会しますか？' }, class: "btn btn-danger btn pull-right group_destroy" %>
    </th>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくグループを作る', new_group_path, class: "new_group btn btn-success btn-lg btn-block" %>

Grouper-Server/app/views/groups/new.html.erb
<h1>グループ作成</h1>

<%= render 'form' %>

<%= link_to '戻る', groups_path, class: "btn btn-default btn-lg btn-block" %>

Grouper-Server/app/views/groups/show.html.erb
<h1 class="group-desc"><%= @group.name %></h1>
<h2 class="group-desc"><%= @group.description %></h2>

<!--
<p>
<strong>作成者</strong><br>
<%= user_name(@group.user_id) %>
</p>

<p>
<strong>詳細</strong><br>
<%= @group.description %>
</p>
<p>
<strong>招待コード</strong>  <%= @group.id %>
</p>
-->
<div class="row">
  <div class="col-sm-12">
    <p><%= link_to 'トーク', {:action=>"index", :controller=>"talk", :anchor=>"talk_fin"}, class: "btn btn-warning btn-lg btn-block" %></p>
  </div>
  <div class="col-xs-6">
    <p><%= link_to 'メンバー', group_members_path(@group), class: "btn btn-primary btn-lg btn-block" %>
  </div>
  <div class="col-xs-6">
    <%= link_to '設定', edit_group_path(@group), class: "btn btn-success btn-lg btn-block" %></p>
  </div>
  <div class="col-xs-6">
    <p><%= link_to '掲示板', group_boards_path(@group), class: 'btn btn-info btn-lg btn-block' %></p>
  </div>
  <div class="col-xs-6">
    <p><%= link_to 'アラーム', group_alarms_path(@group), class: 'btn btn-info btn-lg btn-block' %></p>
  </div>
  <div class="col-xs-12">
    <p><%= link_to '戻る', groups_path, class: 'btn btn-default btn-lg btn-block' %></p>
  </div>
</div>

Grouper-Server/app/views/groups/talk_index.html.erb
<table class="group-table table table-hover">
  <% @groups.each do |group| %>
    <tr class="group-tr">
    <th class="col-xs-2 img">
      <!-- <%= link_to image_tag('dummy.png', class: 'img-circle group-img pull-left', style: 'width: 64px; height: 64px;'), {:action=>"index", :controller=>"talk", :id=>group.id}  %> -->
      <a href="/groups/<%= group.id %>/talk/index#talk_fin">
      <% if File.exist?("./public/img/group/" + group.id.to_s) %>
        <img src="/img/group/<%= group.id %>" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% else %>
        <img src="/group/default.png" class="img-circle group-img" style="width: 64px; height: 64px;">
      <% end %>
    </a>
    </th>
    <th class="col-xs-9 name">
      <!-- <%= link_to group.name, {:action=>"index", :controller=>"talk", :id=>group.id}, class: "group_link" %>-->
      <a href="/groups/<%= group.id %>/talk/index#talk_fin"><%= group.name %></a>
    </th>
    <th class="col-xs-1 remove">
      <%= link_to '退会', group_member_path(group.id, current_user.id), method: :delete, data: {confirm: '本当に退会しますか？' }, class: "btn btn-danger btn pull-right group_destroy" %>
    </th>
  </tr>
<% end %>
</table>
<br>
<%= link_to '新しくグループを作る', new_group_path, class: "new_group btn btn-success btn-lg btn-block" %>