Grouper-Server/config/routes.rb
Rails.application.routes.draw do

  resources :groups do
    resources :members
    resources :alarms do
      member do
        post 'set'
      end
    end
    resources :boards do
      collection do
        get 'edit_index'
      end
    end

    member do
      get 'add_member'
      post 'add_member'
      get 'talk/index'
      post 'talk/index'
      post 'talk/new'
      post 'talk/new_image'
      post 'talk/new_address'
      post 'new_image'
    end
    collection do
      get 'talk_index'
      get 'board_index'
      get 'alarm_index'
      post 'talk/get_address'
    end
  end

  get 'user/find_group'
  post 'user/find_group'
  post 'user/new_image' => 'user#new_image'

  devise_for :users, :controllers => { 
    :sessions => "users/sessions",
    :registrations => 'users/registrations'
  }

  root 'user#index'

end

Grouper-Server/app/models/alarm.rb
class Alarm < ActiveRecord::Base
  belongs_to :group
end

Grouper-Server/app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    group = Group.find(params[:group_id])
    @alarms = group.alarms
  end

  def set
    users = Array.new
    group = Group.find(params[:group_id])
    members = group.members
    members.each do |member|
      users.push User.find(member.user_id)
    end 
    # GCM send
    destination = Array.new
    users.each do |user|
      destination.push user.regid
      puts user.regid
    end
    string = "alarm"
    @alarm = Alarm.find(params[:id])
    hour = @alarm.time.strftime("%H")
    min = @alarm.time.strftime("%M")
    title = @alarm.title
    data = {
      message: string,
      hour: hour,
      min: min,
      title: title
    }

    GCM.send_notification( destination, data )

  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @group = Group.find(params[:group_id])
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
    @group = Group.find(params[:group_id])
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)
    @alarm.group_id = params[:group_id]

    users = Array.new
    group = Group.find(params[:group_id])
    members = group.members
    members.each do |member|
      users.push User.find(member.user_id)
    end 
    # GCM send
    destination = Array.new
    users.each do |user|
      destination.push user.regid
      puts user.regid
    end
    string = "alarm"
    @alarm
    hour = @alarm.time.strftime("%H")
    min = @alarm.time.strftime("%M")
    title = @alarm.title
    data = {
      message: string,
      hour: hour,
      min: min,
      title: title
    }

    GCM.send_notification( destination, data )

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to group_alarms_path, notice: 'アラームが作成されました' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to group_alarms_path, notice: 'アラームを更新しました' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to group_alarms_path, notice: 'アラームを削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:title, :time, :group_id)
    end
end

Grouper-Server/app/helpers/alarms_helper.rb
module AlarmsHelper
end

Grouper-Server/app/views/alarms/_form.html.erb
<%= form_for [@group, @alarm] do |f| %>
  <% if @alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% @alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "タイトル" %><br>
    <%= f.text_area :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit :送信, class: "btn btn-success btn-lg btn-block" %>
  </div>
<% end %>

Grouper-Server/app/views/alarms/edit.html.erb
<%= render 'form' %>

<%= link_to '詳細', group_alarm_path, class: "btn btn-primary btn-lg btn-block" %>
<%= link_to '戻る', group_alarms_path, class: "btn btn-default btn-lg btn-block" %>

Grouper-Server/app/views/alarms/index.html.erb
<h1>アラーム</h1>

<table class="edit_board_all">
  <thead>
    <tr>
      <th class="col-xs-4">タイトル</th>
      <th class="col-xs-6">時刻</th>
      <th class="col-xs-2">編集</th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.each do |alarm| %>
      <tr>
        <td><%= alarm.title %></td>
        <td><%= alarm.time.strftime("%H:%M") %></td>
        <td><%= link_to "詳細" , group_alarm_path(alarm.group_id, alarm), class: "btn btn-primary" %>
        <%= link_to '編集', edit_group_alarm_path(alarm.group_id, alarm), class: "btn btn-success" %>
        <%= link_to '削除', group_alarm_path(alarm.group_id, alarm), method: :delete, data: { confirm: '削除してもいいですか？'}, class: "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいアラーム', new_group_alarm_path, class: "btn btn-lg btn-block btn-success back_to_board" %>

Grouper-Server/app/views/alarms/new.html.erb
<%= render 'form' %>

<%= link_to '戻る', group_alarms_path, class: "btn btn-default btn-lg btn-block" %>

Grouper-Server/app/views/alarms/set.js.erb
$("#set").html("ON");

Grouper-Server/app/views/alarms/show.html.erb
<h1><%= @alarm.title %></h1>

<p>
  <%= @alarm.time.strftime("%H:%M") %>
</p>

<div id="set">
  OFF
  <%= button_to 'セットする', set_group_alarm_path, :remote => true, class: "btn btn-lg btn-success" %><br>
</div>

<%= link_to '詳細', edit_group_alarm_path, class: "btn btn-primary btn-lg btn-block" %>
<%= link_to '戻る', group_alarms_path, class: "btn btn-default btn-lg btn-block" %>